<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SoccerAnalyst.Application\SoccerAnalyst.Application.csproj" />
    <ProjectReference Include="..\SoccerAnalyst.Infrastructure\SoccerAnalyst.Infrastructure.csproj" />
    <ProjectReference Include="..\SoccerAnalyst.Shared\SoccerAnalyst.Shared.csproj" />
  </ItemGroup>

</Project>
